services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.root_dir%/Command'
        tags:
            - console.command

    App\Command\LoaderRunCommand:
        tags:
            -
                name: console.command
                command: app:loaders:run

    App\Command\LoaderListCommand:
        tags:
            -
                name: console.command
                command: app:loaders:list

    App\Command\SyncEntityLengthCachesCommand:
        tags:
            -
                name: console.command
                command: app:util:sync-entity-length-caches

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete

    App\Command\ExportCommand:
        bind:
            $contribDir: '%env(resolve:EXPORT_DEFAULT_PATH)%'
            $dataManagers:
                - '@App\Contrib\Management\Entity\ItemDataManager'
                - '@App\Contrib\Management\Entity\LocationDataManager'
                - '@App\Contrib\Management\Entity\MotionValueDataManager'
                - '@App\Contrib\Management\Entity\SkillDataManager'
                - '@App\Contrib\Management\Entity\CharmDataManager'
                - '@App\Contrib\Management\Entity\DecorationDataManager'
                - '@App\Contrib\Management\Entity\AilmentDataManager'
                - '@App\Contrib\Management\Entity\ArmorSetBonusDataManager'
                - '@App\Contrib\Management\Entity\ArmorDataManager'
                - '@App\Contrib\Management\Entity\ArmorSetDataManager'
                - '@App\Contrib\Management\Entity\WeaponDataManager'
        tags:
            -
                name: console.command
                command: app:export

    App\Command\UserCreateCommand:
        tags:
            -
                name: console.command
                command: app:user:create

    App\Command\ImportCommand:
        tags:
            -
                name: console.command
                command: app:import

    App\Command\ContribPushCommand:
        tags:
            -
                name: console.command
                command: app:contrib:push