services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.project_dir%/src/Command'
        tags:
            - console.command

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete

    App\Command\UserCreateCommand:
        tags:
            -
                name: console.command
                command: app:user:create

    App\Command\WorldEventSyncCommand:
        tags:
            -
                name: console.command
                command: app:events:sync

    App\Command\UserSetPasswordCommand:
        tags:
            -
                name: console.command
                command: app:user:set-password