services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.root_dir%/Command'
        tags:
            - console.command

    App\Command\ScraperRunCommand:
        tags:
            -
                name: console.command
                command: app:scrapers:run

    App\Command\ScraperListCommand:
        tags:
            -
                name: console.command
                command: app:scrapers:list

    App\Command\LoaderRunCommand:
        tags:
            -
                name: console.command
                command: app:loaders:run

    App\Command\LoaderListCommand:
        tags:
            -
                name: console.command
                command: app:loaders:list

    App\Command\SyncEntityLengthCachesCommand:
        tags:
            -
                name: console.command
                command: app:util:sync-entity-length-caches

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete