services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.root_dir%/Command'
        tags:
            - console.command

    App\Command\SyncEntityLengthCachesCommand:
        tags:
            -
                name: console.command
                command: app:util:sync-entity-length-caches

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete

    App\Command\UserCreateCommand:
        tags:
            -
                name: console.command
                command: app:user:create