services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.root_dir%/Command'
        tags:
            - console.command

    App\Command\LoaderRunCommand:
        tags:
            -
                name: console.command
                command: app:loaders:run

    App\Command\LoaderListCommand:
        tags:
            -
                name: console.command
                command: app:loaders:list

    App\Command\SyncEntityLengthCachesCommand:
        tags:
            -
                name: console.command
                command: app:util:sync-entity-length-caches

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete

    App\Command\ExportCommand:
        bind:
            $contribDir: '%env(resolve:EXPORT_DEFAULT_PATH)%'
        tags:
            -
                name: console.command
                command: app:export

    App\Command\UserCreateCommand:
        tags:
            -
                name: console.command
                command: app:user:create

    App\Command\ImportCommand:
        tags:
            -
                name: console.command
                command: app:import

    App\Command\ContribPushCommand:
        tags:
            -
                name: console.command
                command: app:contrib:push