services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Command\:
        resource: '%kernel.root_dir%/Command'
        tags:
            - console.command

    App\Command\ScrapeCommand:
        tags:
            -
                name: console.command
                command: app:scrape

    App\Command\ScraperListCommand:
        tags:
            -
                name: console.command
                command: app:scrape:list

    App\Command\SyncEntityLengthCachesCommand:
        tags:
            -
                name: console.command
                command: app:util:sync-entity-length-caches

    App\Command\MHWGSyncSharpnessValues:
        tags:
            -
                name: console.command
                command: app:fix:sync-mhwg-sharpness-values

    App\Command\EntityDeleteCommand:
        tags:
            -
                name: console.command
                command: app:entity:delete