services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Contrib\BucketManager:
        bind:
            $bucket: '%env(resolve:ASSETS_BUCKET_NAME)%'

    App\Contrib\Transformers\AilmentTransformer: ~
    App\Contrib\Transformers\ArmorTransformer: ~
    App\Contrib\Transformers\ArmorSetTransformer: ~
    App\Contrib\Transformers\CharmTransformer: ~
    App\Contrib\Transformers\DecorationTransformer: ~