services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Contrib\TransformerManager:
        arguments:
            -
                - '@App\Contrib\Transformers\AilmentTransformer'

    App\Contrib\Transformers\AilmentTransformer: ~