services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Export\ExportManager:
        arguments:
            -
                - '@App\Export\Exporters\AilmentExporter'
                - '@App\Export\Exporters\ArmorExporter'
                - '@App\Export\Exporters\ArmorSetExporter'
                - '@App\Export\Exporters\CharmExporter'
                - '@App\Export\Exporters\DecorationExporter'
                - '@App\Export\Exporters\ItemExporter'
                - '@App\Export\Exporters\LocationExporter'
                - '@App\Export\Exporters\MotionValueExporter'
                - '@App\Export\Exporters\MonsterExporter'
                - '@App\Export\Exporters\SkillExporter'
                - '@App\Export\Exporters\WeaponExporter'

    App\Export\ExportHelper: ~

    App\Export\Exporters\AilmentExporter: ~
    App\Export\Exporters\ArmorExporter: ~
    App\Export\Exporters\ArmorSetExporter: ~
    App\Export\Exporters\CharmExporter: ~
    App\Export\Exporters\DecorationExporter: ~
    App\Export\Exporters\ItemExporter: ~
    App\Export\Exporters\LocationExporter: ~
    App\Export\Exporters\MotionValueExporter: ~
    App\Export\Exporters\MonsterExporter: ~
    App\Export\Exporters\SkillExporter: ~
    App\Export\Exporters\WeaponExporter: ~