services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Export\ExportManager:
        arguments:
            -
                - '@App\Export\Exporters\AilmentExporter'
                - '@App\Export\Exporters\ArmorExporter'
                - '@App\Export\Exporters\WeaponExporter'

    App\Export\Exporters\AilmentExporter: ~
    App\Export\Exporters\ArmorExporter: ~
    App\Export\Exporters\WeaponExporter: ~