services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Import\ImportManager:
        arguments:
            -
                - '@App\Import\Importers\ItemImporter'
                - '@App\Import\Importers\AilmentImporter'
                - '@App\Import\Importers\ArmorImporter'
                - '@App\Import\Importers\ArmorSetImporter'
                - '@App\Import\Importers\CharmImporter'
                - '@App\Import\Importers\DecorationImporter'
                - '@App\Import\Importers\LocationImporter'

    App\Import\AssetManager:
        bind:
            $bucket: '%env(resolve:ASSETS_BUCKET_NAME)%'

    App\Import\Importers\AilmentImporter: ~
    App\Import\Importers\ArmorImporter: ~
    App\Import\Importers\ArmorSetImporter: ~
    App\Import\Importers\CharmImporter: ~
    App\Import\Importers\DecorationImporter: ~
    App\Import\Importers\ItemImporter: ~
    App\Import\Importers\LocationImporter: ~