services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\Event\Listeners\UserActivationEmailListener:
        tags:
            -
                name: kernel.event_listener
                event: api.entity.create
                method: onUserCreate