services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    app.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@serializer.normalizer.datetime'
                - '@App\Serializer\CustomObjectNormalizer'
            -
                - '@serializer.encoder.json'

    App\Serializer\CustomObjectNormalizer:
        bind:
            $defaultContext:
                preserve_empty_objects: true

    DaybreakStudios\RestApiCommon\Responder:
        bind:
            $serializer: '@app.serializer'

    DaybreakStudios\RestApiCommon\ResponderInterface: '@DaybreakStudios\RestApiCommon\Responder'

    DaybreakStudios\RestApiCommon\ResponderService: ~
