services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Scraping\ScraperCollection:
        arguments:
            -
                - '@App\Scraping\Scrapers\MHWikiaItemsScraper'
                - '@App\Scraping\Scrapers\KiranicoSkillsScraper'
                - '@App\Scraping\Scrapers\KiranicoCharmsScraper'
                - '@App\Scraping\Scrapers\FextralifeCharmRarityScraper'
                - '@App\Scraping\Scrapers\MHWikiaWeaponScraper'
                - '@App\Scraping\Scrapers\MHWorldDataArmorScraper'
                - '@App\Scraping\Scrapers\KiranicoDecorationsScraper'
                - '@App\Scraping\Scrapers\MHWikiaWeaponIconsScraper'
                - '@App\Scraping\Scrapers\FextralifeWeaponImagesScraper'
                - '@App\Scraping\Scrapers\KiranicoMotionValuesScraper'

    App\Scraping\Configurations\KiranicoConfiguration: ~
    App\Scraping\Configurations\MHWikiaConfiguration: ~
    App\Scraping\Configurations\FextralifeConfiguration: ~
    App\Scraping\Configurations\GithubConfiguration: ~

    App\Scraping\Scrapers\MHWikiaItemsScraper: ~
    App\Scraping\Scrapers\KiranicoSkillsScraper: ~
    App\Scraping\Scrapers\KiranicoCharmsScraper: ~
    App\Scraping\Scrapers\FextralifeCharmRarityScraper: ~
    App\Scraping\Scrapers\MHWikiaWeaponScraper: ~
    App\Scraping\Scrapers\MHWorldDataArmorScraper: ~
    App\Scraping\Scrapers\KiranicoDecorationsScraper: ~
    App\Scraping\Scrapers\MHWikiaWeaponIconsScraper: ~
    App\Scraping\Scrapers\FextralifeWeaponImagesScraper: ~
    App\Scraping\Scrapers\KiranicoMotionValuesScraper: ~