parameters:
    app.security.user_repository: App\Entity\User

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    DaybreakStudios\VeritasBundle\Security\Core\User\JWTEntityUserProvider:
        public: true
        arguments:
            - '@doctrine'
            - '%app.security.user_repository%'