services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    DaybreakStudios\RestApiCommon\Event\Listeners\LexikJwtAuthenticationFailureSubscriber:
        tags:
            - kernel.event_subscriber

    App\Security\CustomizePayloadListener:
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_jwt_created
                method: onJwtCreate

    App\Security\DisabledUserChecker: ~