api.armor.list:
    methods:
        - GET
    path: /armor
    controller: 'App\Controller\ArmorDataController::listAction'

api.armor.read:
    methods:
        - GET
    path: /armor/{idOrSlug}
    controller: 'App\Controller\ArmorDataController::readAction'