api.armor_sets.list:
    methods:
        - GET
    path: /armor/sets
    controller: 'App\Controller\ArmorSetsDataController::listAction'

api.armor_sets.read:
    methods:
        - GET
    path: /armor/sets/{id}
    controller: 'App\Controller\ArmorSetsDataController::readAction'

api.armor.list:
    methods:
        - GET
    path: /armor
    controller: 'App\Controller\ArmorDataController::listAction'

api.armor.read:
    methods:
        - GET
    path: /armor/{idOrSlug}
    controller: 'App\Controller\ArmorDataController::readAction'