api.decorations.list:
    methods:
        - GET
    path: /decorations
    controller: 'App\Controller\DecorationsDataController::listAction'

api.decorations.read:
    methods:
        - GET
    path: /decorations/{idOrSlug}
    controller: 'App\Controller\DecorationsDataController::readAction'