api.monsters.list:
    path: /monsters
    methods:
        - GET
    controller: 'App\Controller\MonsterDataController::listAction'

api.monsters.read:
    path: /monsters/{idOrSlug}
    methods:
        - GET
    controller: 'App\Controller\MonsterDataController::readAction'