api.skills.list:
    methods:
        - GET
    path: /skills
    controller: 'App\Controller\SkillsDataController::listAction'

api.skills.read:
    methods:
        - GET
    path: /skills/{idOrSlug}
    controller: 'App\Controller\SkillsDataController::readAction'