api.weapons.list:
    methods:
        - GET
    path: /weapons
    controller: 'App\Controller\WeaponsDataController::listAction'

api.weapons.read:
    methods:
        - GET
    path: /weapons/{idOrSlug}
    controller: 'App\Controller\WeaponsDataController::readAction'