api.weapons.list:
    methods:
        - GET
    path: /weapons
    controller: 'App\Controller\WeaponsDataController::listAction'

api.weapons.list-by-type:
    methods:
        - GET
    path: /weapons/{type}
    controller: 'App\Controller\WeaponsDataController::listByTypeAction'
    requirements:
        type: great-sword|long-sword|sword-and-shield|dual-blades|hammer|hunting-horn|lance|gunlance|switch-axe|charge-blade|insect-glaive|light-bowgun|heavy-bowgun|bow

api.weapons.read:
    methods:
        - GET
    path: /weapons/{idOrSlug}
    controller: 'App\Controller\WeaponsDataController::readAction'