api.weapon-upgrade-tree.list:
    methods:
        - GET
    path: /weapon-upgrade-tree
    controller: 'App\Controller\WeaponUpgradesDataController::listAction'

api.weapon-upgrade-tree.for-weapon:
    methods:
        - GET
    path: /weapon-upgrade-tree/for-weapon/{idOrSlug}
    controller: 'App\Controller\WeaponUpgradesDataController::forWeaponAction'

api.weapon-upgrade-tree.read:
    methods:
        - GET
    path: /weapon-upgrade-tree/{idOrSlug}
    controller: 'App\Controller\WeaponUpgradesDataController::readAction'