app._annotations:
    resource: '../src/Controller/'
    type: annotation
    defaults:
        _format: json

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: 'https://docs.mhw-db.com/'

auth.login:
    path: /auth