api._routes:
    resource: 'routes/api'
    type: directory

index:
    path: /
    controller: 'FrameworkBundle:Redirect:urlRedirect'
    defaults:
        path: 'https://larttyler.github.io/MHWDB-Docs/'