app._annotations:
    resource: '../src/Controller/'
    type: annotation
    defaults:
        _format: json

index:
    path: /
    controller: 'FrameworkBundle:Redirect:urlRedirect'
    defaults:
        path: 'https://docs.mhw-db.com/'

auth:
    path: /auth