imports:
    -
        resource: './services'
        type: 'directory'

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\QueryDocument\ApiQueryManager:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    Aws\Sdk:
        arguments:
            -
                region: 'us-east-2'
                version: 'latest'

    App\Doctrine\LengthCachingListener:
        tags:
            -
                name: doctrine.event_listener
                event: prePersist
            -
                name: doctrine.event_listener
                event: preUpdate

    App\WorldEvent\WorldEventReader: ~