imports:
    -
        resource: './services'
        type: 'directory'

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\QueryDocument\ApiQueryManager:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    DaybreakStudios\DoctrineQueryDocument\QueryManagerInterface: '@App\QueryDocument\ApiQueryManager'

    Aws\Sdk:
        arguments:
            -
                region: 'us-east-2'
                version: 'latest'

    App\WorldEvent\WorldEventReader: ~