App\Entity\ArmorSet:
    type: entity
    table: armor_sets
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        rank:
            type: string
            length: 32
            nullable: false
    oneToMany:
        pieces:
            targetEntity: App\Entity\Armor
            mappedBy: armorSet
    manyToOne:
        bonus:
            targetEntity: App\Entity\ArmorSetBonus
            joinColumn:
                nullable: true
                options:
                    unsigned: true