App\Entity\ArmorSetBonus:
    type: entity
    table: armor_set_bonuses
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
    oneToMany:
        ranks:
            targetEntity: App\Entity\ArmorSetBonusRank
            mappedBy: bonus
            orphanRemoval: true
            cascade:
                - all