App\Entity\ArmorCraftingInfo:
    type: entity
    table: armor_crafting_info
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        materialsLength:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
            column: materials_length
    manyToMany:
        materials:
            targetEntity: App\Entity\CraftingMaterialCost
            orphanRemoval: true
            cascade:
                - all
            joinTable:
                name: armor_crafting_material_costs
                joinColumns:
                    armor_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    crafting_material_cost_id:
                        nullable: false
                        unique: true
                        options:
                            unsigned: true