App\Entity\ArmorSetBonusRank:
    type: entity
    table: armor_set_bonus_ranks
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        pieces:
            type: smallint
            nullable: false
            options:
                unsigned: true
    manyToOne:
        bonus:
            targetEntity: App\Entity\ArmorSetBonus
            inversedBy: ranks
            joinColumn:
                nullable: false
                options:
                    unsigned: true
        skill:
            targetEntity: App\Entity\SkillRank
            joinColumn:
                nullable: false
                options:
                    unsigned: true