App\Entity\ArmorAssets:
    type: entity
    table: armor_assets
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    oneToOne:
        imageMale:
            targetEntity: App\Entity\Asset
            cascade:
                - persist
            joinColumn:
                nullable: false
                options:
                    unsigned: true
        imageFemale:
            targetEntity: App\Entity\Asset
            cascade:
                - persist
            joinColumn:
                nullable: false
                options:
                    unsigned: true