App\Entity\Asset:
    type: entity
    table: assets
    uniqueConstraints:
        hash_idx:
            columns:
                - primary_hash
                - secondary_hash
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        uri:
            type: string
            length: 254
            nullable: false
        primaryHash:
            type: string
            length: 128
            nullable: false
            column: primary_hash
        secondaryHash:
            type: string
            length: 128
            nullable: false
            column: secondary_hash