App\Entity\CraftingMaterialCost:
    type: entity
    table: crafting_material_costs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        item:
            targetEntity: App\Entity\Item
            joinColumn:
                nullable: false
                options:
                    unsigned: true