App\Entity\Decoration:
    type: entity
    table: decorations
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
        rarity:
            type: smallint
            nullable: false
            options:
                unsigned: true
        slot:
            type: smallint
            nullable: false
            options:
                unsigned: true
    oneToOne:
        # DEPRECATED This field preserves BC for < 1.9.0 and will be removed in the future
        skill:
            targetEntity: App\Entity\Skill
            joinColumn:
                nullable: false
                options:
                    unsigned: true
    manyToMany:
        skills:
            targetEntity: App\Entity\SkillRank
            joinTable:
                name: decorations_skill_ranks
                joinColumns:
                    decoration_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    skill_rank_id:
                        nullable: false
                        options:
                            unsigned: true