App\Entity\Item:
    type: entity
    table: items
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        description:
            type: text
            nullable: false
        rarity:
            type: smallint
            nullable: false
            options:
                unsigned: true
        sellPrice:
            type: integer
            nullable: false
            options:
                unsigned: true
        buyPrice:
            type: integer
            nullable: false
            options:
                unsigned: true
        carryLimit:
            type: integer
            nullable: false
            options:
                unsigned: true