App\Entity\MotionValue:
    type: entity
    table: motion_values
    uniqueConstraints:
        name_weapon_type_idx:
            columns:
                - weapon_type
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
        weaponType:
            type: string
            length: 32
            nullable: false
            column: weapon_type
        damageType:
            type: string
            length: 32
            nullable: true
            column: damage_type
        stun:
            type: smallint
            nullable: true
            options:
                unsigned: true
            column: stun_potency
        exhaust:
            type: smallint
            nullable: true
            options:
                unsigned: true
            column: exhaust_potency
        hits:
            type: json
            nullable: false