App\Entity\Skill:
    type: entity
    table: skills
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        description:
            type: text
            nullable: false
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
        ranksLength:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
            column: ranks_length
    oneToMany:
        ranks:
            targetEntity: App\Entity\SkillRank
            mappedBy: skill
            orphanRemoval: true
            cascade:
                - all