App\Entity\Weapon:
    type: entity
    table: weapons
    indexes:
        type_idx:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        type:
            type: string
            length: 32
            nullable: false
        rarity:
            type: smallint
            nullable: false
            options:
                unsigned: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
        attributes:
            type: json
            nullable: false
        elementsLength:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
            column: elements_length
        slotsLength:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
            column: slots_length
        durabilityLength:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
            column: durability_length
    embedded:
        attack:
            class: App\Entity\WeaponAttackValues
            prefix: attack_
    oneToOne:
        crafting:
            targetEntity: App\Entity\WeaponCraftingInfo
            orphanRemoval: true
            cascade:
                - all
            joinColumn:
                nullable: true
                options:
                    unsigned: true
        assets:
            targetEntity: App\Entity\WeaponAssets
            orphanRemoval: true
            cascade:
                - all
            joinColumn:
                nullable: true
                options:
                    unsigned: true
        sharpness:
            targetEntity: App\Entity\WeaponSharpness
            orphanRemoval: true
            cascade:
                - all
            joinColumn:
                nullable: false
                options:
                    unsigned: true
    oneToMany:
        elements:
            targetEntity: App\Entity\WeaponElement
            mappedBy: weapon
            orphanRemoval: true
            cascade:
                - all
    manyToMany:
        slots:
            targetEntity: App\Entity\Slot
            orphanRemoval: true
            cascade:
                - all
            joinTable:
                name: weapon_slots
                joinColumns:
                    weapon_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    slot_id:
                        nullable: false
                        options:
                            unsigned: true
        durability:
            targetEntity: App\Entity\WeaponSharpness
            orphanRemoval: true
            cascade:
                - all
            joinTable:
                name: weapon_durability
                joinColumns:
                    weapon_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    sharpness_id:
                        nullable: false
                        options:
                            unsigned: true