App\Entity\WeaponAssets:
    type: entity
    table: weapon_assets
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    oneToOne:
        icon:
            targetEntity: App\Entity\Asset
            cascade:
                - persist
            joinColumn:
                nullable: true
                options:
                    unsigned: true
        image:
            targetEntity: App\Entity\Asset
            cascade:
                - persist
            joinColumn:
                nullable: true
                options:
                    unsigned: true