App\Entity\Weapon:
    type: entity
    table: weapons
    indexes:
        type_idx:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        type:
            type: string
            length: 32
            nullable: false
        rarity:
            type: smallint
            nullable: false
            options:
                unsigned: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
        attributes:
            type: json
            nullable: false
    oneToOne:
        crafting:
            targetEntity: App\Entity\WeaponCraftingInfo
            orphanRemoval: true
            cascade:
                - persist
            joinColumn:
                nullable: true
                options:
                    unsigned: true