App\Entity\Charm:
    type: entity
    table: charms
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
    manyToMany:
        skills:
            targetEntity: App\Entity\SkillRank
            joinTable:
                name: charms_skill_ranks
                joinColumns:
                    charm_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    skill_rank_id:
                        nullable: false
                        options:
                            unsigned: true