App\Entity\Decoration:
    type: entity
    table: decorations
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
        rarity:
            type: smallint
            nullable: false
            options:
                unsigned: true
        slot:
            type: smallint
            nullable: false
            options:
                unsigned: true
    oneToOne:
        skill:
            targetEntity: App\Entity\Skill
            joinColumn:
                nullable: false
                options:
                    unsigned: true